version: '2'

services:
  frontend:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/project
  backend:
    image: openjdk:8-alpine
    volumes:
      - ./backend/target/scala-2.12/NdGameOfLife-assembly-0.1.0-SNAPSHOT.jar:/app.jar
    command: ["java", "-jar", "/app.jar"]
