export const FETCH_MOVE_REQUEST = 'FETCH_MOVE_REQUEST';
export const FETCH_MOVE_FAILURE = 'FETCH_MOVE_FAILURE';
export const FETCH_MOVE_SUCCESS = 'FETCH_MOVE_SUCCESS';

export const TURN_CELL_ON = 'TURN_CELL_ON';
export const TURN_CELL_OFF = 'TURN_CELL_OFF';
